apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  selector:
    app: primeiro-pod
  type: NodePort
  ports:
    - port: 80 # porta service
      targetPort: 80 # porta container
      nodePort: 30000 # porta externa